version: 2

updates:
  - package-ecosystem: github-actions
    directory: /go-library/.github/workflows
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /go-service/
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /go-service/.github/workflows
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /go-simple-cli/.github/workflows
    schedule:
      interval: daily
